backend:
  name: github
  repo: EstebanMendez01/repo   # Replace with your GitHub repository

media_folder: src/assets
public_folder: /public

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
